Web.View Curso/Models/ErrorViewModel.cs
namespace Web.View_Curso.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web.View Curso/Controllers/AlunoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Curso.Model;
using Curso.Model.Repositories;
using Curso.Model.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Web.View_Curso.Controllers
{
    public class AlunoController : Controller
    {
        // GET: AlunoController
        public ActionResult Index()
        {
            RepositoryAluno oRepository = new RepositoryAluno();
            List<Aluno> oLista = oRepository.SelecionarTodos();
            return View(oLista);
        }

        // GET: AlunoController/Details/5
        public ActionResult Details(int CodigoCurso)
        {
            RepositoryAluno oRepository = new RepositoryAluno();
            Aluno oAluno = oRepository.SelecionaId(CodigoCurso);
            return View(oAluno);
        }

        // GET: AlunoController/Create
        public ActionResult Create()
        {
            Aluno oAluno = new Aluno();
            return View(oAluno);
        }

        // POST: AlunoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aluno oAluno)
        {
            RepositoryAluno oRepository = new RepositoryAluno();
            oRepository.Incluir(oAluno);
            return View("Index", oRepository.SelecionarTodos());
        }

        // GET: AlunoController/Edit/5
        public ActionResult Edit(int CodigoCurso)
        {
            RepositoryAluno oRepository = new RepositoryAluno();
            Aluno oAluno = oRepository.SelecionaId(CodigoCurso);
            return View(oAluno);
        }

        // POST: AlunoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Aluno oAluno)
        {

            RepositoryAluno oRepository = new RepositoryAluno();
            oRepository.Alterar(oAluno);
            return View(oAluno);

        }

        // GET: AlunoController/Delete/5
        public ActionResult Delete(int CodigoCurso)
        {
            RepositoryAluno oRepository = new RepositoryAluno();
            oRepository.Excluir(CodigoCurso);
            return View();
        }

        // POST: AlunoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Web.View Curso/Controllers/AulasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Curso.Model;
using Curso.Model.Repositories;
using Curso.Model.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Web.View_Curso.Controllers
{
    public class AulasController : Controller
    {
        // GET: AulasController
        public ActionResult Index()
        {
            RepositoryAula oRepository= new RepositoryAula();
            List<Aula> oLista = oRepository.SelecionarTodos();
            return View(oLista);
        }

        // GET: AulasController/Details/5
        public ActionResult Details(int id)
        {
            RepositoryAula oRepository = new RepositoryAula();
            Aula oAula = oRepository.SelecionaId(id);
            return View(oAula);
        }

        // GET: AulasController/Create
        public ActionResult Create()
        {
            Aula oAula = new Aula();
            return View(oAula);
        }

        // POST: AulasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aula oAula)
        {
            RepositoryAula oRepository = new RepositoryAula();
            oRepository.Incluir(oAula);
            return View("Index", oRepository.SelecionarTodos());
        }

        // GET: AulasController/Edit/5
        public ActionResult Edit(int id)
        {
            RepositoryAula oRepository = new RepositoryAula();
            Aula oAula = oRepository.SelecionaId(id);
            return View(oAula);
        }

        // POST: AulasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Aula oAula)
        {
            
                RepositoryAula oRepository = new RepositoryAula();
                oRepository.Alterar(oAula);
                return View(oAula);
           
        }

        // GET: AulasController/Delete/5
        public ActionResult Delete(int id)
        {
            RepositoryAula oRepository = new RepositoryAula();
            oRepository.Excluir(id);
            return View();
        }

        // POST: AulasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Web.View Curso/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web.View_Curso.Models;

namespace Web.View_Curso.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web.View Curso/Views/Aluno/Create.cshtml
@model Curso.Model.Models.Aluno

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoCurso" class="control-label"></label>
                <input asp-for="CodigoCurso" class="form-control" />
                <span asp-validation-for="CodigoCurso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web.View Curso/Views/Aluno/Delete.cshtml
@model Curso.Model.Models.Aluno

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Matricula" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web.View Curso/Views/Aluno/Details.cshtml
@model Curso.Model.Models.Aluno

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class="col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoCurso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoCurso)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Matricula">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web.View Curso/Views/Aluno/Edit.cshtml
@model Curso.Model.Models.Aluno

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Matricula" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web.View Curso/Views/Aluno/Index.cshtml
@model IEnumerable<Curso.Model.Models.Aluno>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodigoCurso)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                 <td>
                    @Html.DisplayFor(modelItem => item.Matricula)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodigoCurso)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Matricula">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Matricula">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Matricula">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Web.View Curso/Views/Aulas/Create.cshtml
@model Curso.Model.Models.Aula

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Aula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>



            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web.View Curso/Views/Aulas/Delete.cshtml
@model Curso.Model.Models.Aula

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aula</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Codigo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web.View Curso/Views/Aulas/Details.cshtml
@model Curso.Model.Models.Aula

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Aula</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
         <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Codigo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web.View Curso/Views/Aulas/Edit.cshtml
@model Curso.Model.Models.Aula

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Aula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Codigo" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web.View Curso/Views/Aulas/Index.cshtml
@model IEnumerable<Curso.Model.Models.Aula>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>

            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Codigo">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Codigo">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Codigo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Web.View Curso/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web.View Curso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.View_Curso</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.View_Curso.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web.View_Curso</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aulas" asp-action="Index">Aula</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Web.View_Curso - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>